### ISSUE TITLE
Input in the middle not recorded. help

### ISSUE THREAD

**Issue by efortes** [ihatecsv/ControlStadia#14]
After a whole afternoon trying to fix this issue I wanted to ask the question here.
The plugin works but I have the following problem with my Logitech g29 wheel:

Lets say the x axis goes from -100 to 100 ( left and right). The first 10 to the left or to the right are detected to late. Can something be done about this?

I'm  trying to make the wheel work with Stadia.

**Comment by hankbinkle** [comment]
In F1 2020 for example you can play with the steering dead zone, saturation, and scale... might help if your game can manage some in-game settings?

**Comment by Bob4040** [comment]
F1 2020 seems to have a programmed deadzone in the centre few degrees for a controller, that you can't get rid of. There must be specific coding for a actual wheel inputs that would typically get rid of this for other ports.
Ex  Gamepad tester and driver shower wheel has no deadzone, but F1 doesn't pick up the first few degrees.

**Comment by efortes** [comment]
Thank you for the answer all. I gave up the try a ahilw ago.
